### ISSUE TITLE
releases to match flux2 releases?

### ISSUE THREAD

**Issue by cawolf** [nicholaswilde/ansible-role-flux#1]
Hey @nicholaswilde, 
I just stumbled upon this role, which seems fitting my needs perfectly.
However, as flux2 is evolving very fast, I was wondering if you could somehow automate the maintenance of new releases to support new versions of flux2 faster (right now, the role supports up to flux2 0.7.5, and 0.7.6, 0.7.7, 0.8.0 are released). Is it possible, or do you need to make manual steps to make the role work with newer versions?
Thanks and keep up the good work,
best regards,
@cawolf

**Comment by nicholaswilde** [comment]
I thought the upgrade was going to be simple but I'm running into some `molecule` issues which might be related to [#2560](https://github.com/ansible-community/molecule/issues/2560). I don't have the time to look into it at this very moment but you're welcome to try.

Follow the directions in the [Testing section](https://github.com/nicholaswilde/ansible-role-flux#testing) first then do the following:
```shell
# Use the dl-checksum.sh file to get the checksums
$ ./dl-checksum.sh 8.0.0
# Copy the checksums to the defaults/main.yaml file
# Update the following variables
...
app_ver: 0.8.0
app_os: linux
app_arch: amd64
...
$ molecule test
```

**Comment by cawolf** [comment]
Hi,

unfortunatley, I do not find the time to contribute to this role.

In the meantime, I created a very small playbook, which utilizes `flux bootstrap` for the initial setup, which works fine for me.

I will close this issue for now, as I will not need this functionality anymore. Feel free to reopen it anytime.

Thanks again,
best regards,
@cawolf
